### ISSUE TITLE
How to solve No such file or directory: 'nyu_class_list.json'?

### ISSUE THREAD

**Issue by DaDudeIan** [Lavreniuk/EVP#10]
After fixing issue #8 for my own project, I am now running into the problem in the title. I've tried uncommenting lines 38-39 from `depth/dump_nyu_text_embeddings.py` as this seems to be where the file should be created. Meaning, this:
```python
38 | #with open('nyu_class_list.json', 'w') as f:
39 | #    f.write(json.dumps(class_name))
```
is now this:
```python
38 | with open('nyu_class_list.json', 'w') as f:
39 |     f.write(json.dumps(class_name))
```
But this hasn't fixed the issue

**Comment by Lavreniuk** [comment]
hi, @DaDudeIan , thanks for interesting in EVP. Sorry for bug, it is left from VPD model code, but in EVP we don't need the class names or numbers. So class_id or nyu_class_list.json is not needed.
I have update the git this class_id =0 for nyu same as it was for KITTI.
Please try it now.

**Comment by DaDudeIan** [comment]
This fixed the error, thank you!
