### ISSUE TITLE
GPU performance is needed?

### ISSUE THREAD

**Issue by RuiTianHIT** [Lavreniuk/EVP#13]
Hi!!!
How much GPU memory is required for the train and test process? 
I use RTX3090 to reproduce on the NYUV2 dataset, which shows the cuda out memory.
Thank you very much!
 Looking forward to your reply!

**Comment by Lavreniuk** [comment]
hi, @RuiTianHIT, I have utilized GPU with 48Gb of VRAM. (1 is enough, but more is better for faster training).

**Comment by DaDudeIan** [comment]
Hey @Lavreniuk. I've tried training it on 2xRTX 3060 with 12 GB each, but also run it the `cuda.OutOfMemoryError` error. Is there somewhere in the code we should change something so this doesn't happen?

**Comment by Lavreniuk** [comment]
@DaDudeIan , unfortunately no, our model utilized Stable diffusion v1.5 as a backbone and it is really big backbone...
