### ISSUE TITLE
How to generate text embedding in custom datasets, such as nuScenes datasets?

### ISSUE THREAD

**Issue by RuiTianHIT** [Lavreniuk/EVP#14]
@Lavreniuk 

Hello author!
Recently, I've been bothering you a lot because your work is of very high quality and I'm very interested.
Could you please tell me how to generate text embeddings for my own dataset? such as nuScenes datasets.
Thank you to the author.
Looking forward to your reply!

**Comment by Lavreniuk** [comment]
@RuiTianHIT , thanks for your interest in our work!
please check this file:
https://github.com/Lavreniuk/EVP/blob/main/depth/dump_nyu_text_embeddings.py
and adapt it to your new dataset
