### ISSUE TITLE
load the pre-trained model and resume weights

### ISSUE THREAD

**Issue by RuiTianHIT** [Lavreniuk/EVP#16]
@Lavreniuk 
Hello author, thank you for such high-quality work
I would like to ask how to load the pre-trained model and resume weights
Looking forward to your reply, thank you again！

**Comment by Lavreniuk** [comment]
hi, @RuiTianHIT , thank you in interested in the EVP.
Please check in the training file: resume_from argument and the file name structure (you need just rename file in proper way and run training using this argument). It is same way as commonly in torch, you just load pretrained weights before training and update epochs num from the file name, and that's it.
