### ISSUE TITLE
Is the train.sh file missing?

### ISSUE THREAD

**Issue by junwei0812** [Lavreniuk/EVP#2]

**Comment by Lavreniuk** [comment]
@junwei0812, thank you for your interest in our model. 
Currently, the Git repository contains only the inference code and trained models. The training code for reproduction will be added soon. You can check the HF demo and try the model with your data there. If you wish to fine-tune it on a custom dataset, you will need to wait a little bit or write your own code for this.

**Comment by junwei0812** [comment]
> @junwei0812, thank you for your interest in our model. Currently, the Git repository contains only the inference code and trained models. The training code for reproduction will be added soon. You can check the HF demo and try the model with your data there. If you wish to fine-tune it on a custom dataset, you will need to wait a little bit or write your own code for this.

thanks

**Comment by Lavreniuk** [comment]
Hi, @junwei0812
Sorry for delay, I have finally released all training scripts!
Feel free to run it. Hope you will enjoy it!
