### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by agneet42** [Lavreniuk/EVP#5]
Hello! I had a couple of questions : 

1. Which data is the currently publicly available checkpoint trained on? 
2. When can we expect the reproducible training and evaluation code to be available?

**Comment by Lavreniuk** [comment]
@agneet42, thanks for interesting. Currently publicly available checkpoint trained on NYU dataset.
training and evaluation code will be published a little bit later.

**Comment by Lavreniuk** [comment]
Hi, @agneet42,
Sorry for delay, I have finally released all training scripts!
Feel free to run it. Hope you will enjoy it!
